server:
  port: 8081

spring:
  application:
    name: auction-notification

  data:
    redis:
      ssl:
        enabled: ${REDIS_SSL_ENABLED:false}
      host: ${REDIS_HOST:localhost}
      port: 6379

  cloud:
    aws:
      parameterstore:
        enabled: false

  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      show-details: never

jwt:
  secret:
    key: ${JWT_SECRET}
  accessExpire: 1800000
  refreshExpire: 604800000
