spring:
  application:
    name: auction-notification

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:9092

  cloud:
    aws:
      parameterstore:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      show-details: never

jwt:
  secret:
    key: ${JWT_SECRET}
  accessExpire: 1800000
  refreshExpire: 604800000